export const STRINGS = {
    appName: 'PillPal',
    appEmoji: '💊 ✨ 🔥',
    title: 'Your health streak starts here',
    subtitle: 'Never miss a dose again 💪',
    chipStreaks: '🔥 Streaks',
    chipAchievements: '🏆 Achievements',
    chipReminders: '💊 Reminders',
    footerLoading: 'Getting things ready...',
    happy: 'happy',
    sad: 'sad',
    idle: 'idle',
    taken: 'taken',
    skipped: 'skipped',
    pending: 'pending',
    defaultError: 'Something went wrong!',
    loginTagline: "Keep your streak alive! 🔥",
    emailLabel: "📧 Email",
    passwordLabel: "🔒 Password",
    forgotPassword: "Forgot password? 🤔",
    loginButton: "Let's Go! 🚀",
    loadingText: "Loading your streak...",
    joinBannerTitle: "Join 10,000+ streak champions",
    joinBannerSubtitle: "Your best streak awaits you!",
    signupText: "New here?",
    signupButton: "Start your streak! ✨",
    bottomTitle: "🔥 Don't break the chain — log in daily!",
    averageText: "Average user streak:",
    achievementsTitle: "Unlock achievements 🎖️"
} as const;