export const STRINGS = {
    appName: 'PillPal',
    appEmoji: '💊 ✨ 🔥',
    title: 'Your health streak starts here',
    subtitle: 'Never miss a dose again 💪',
    chipStreaks: '🔥 Streaks',
    chipAchievements: '🏆 Achievements',
    chipReminders: '💊 Reminders',
    footerLoading: 'Getting things ready...',
    happy: 'happy',
    sad: 'sad',
    idle: 'idle',
    taken: 'taken',
    skipped: 'skipped',
    pending: 'pending',
    defaultError: 'Something went wrong!',
    loginTagline: "Keep your streak alive! 🔥",
    emailLabel: "📧 Email",
    passwordLabel: "🔒 Password",
    forgotPassword: "Forgot password? 🤔",
    loginButton: "Let's Go! 🚀",
    loadingText: "Loading your streak...",
    joinBannerTitle: "Join 10,000+ streak champions",
    joinBannerSubtitle: "Your best streak awaits you!",
    signupText: "New here?",
    signupButton: "Start your streak! ✨",
    bottomTitle: "🔥 Don't break the chain — log in daily!",
    averageText: "Average user streak:",
    achievementsTitle: "Unlock achievements 🎖️",
    levelUpMessage: 'Level Up!',
    celebrationMsg: ['Awesome!',
        'Keep it up!',
        "You're on fire!",
        'Healthy habit!',],
    signUpSubtitle: "Your streak starts today! ✨",

    nameLabel: "👤 Your Name",
    confirmPasswordLabel: "✅ Confirm Password",
    namePlaceholder: "Alex Johnson",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "••••••••",
    createButton: "Start My Streak! 🔥",
    loadingButton: "Creating your streak...",
    bannerTitle: "Join 10,000+ streak champions",
    bannerSubtitle: "Build healthy habits, one day at a time",
    terms:
        "By signing up you agree to our Terms & Privacy Policy",
    alreadyUser: "Already a streak champion?",
    login: "Log in! 🏆",
    habitMessage: "🌟 It only takes 21 days to build a habit!",
    successMessage: "📩 Verification email sent. Please verify before login.",
    signUpErrorTitle: '⚠️ Sign Up Failed',
 nameError: 'What should we call you? 🤔',
 validEmail :'Need a valid email! 📧',
 passReq : '6+ chars, 1 Capital, 1 Number & 1 Special 🔒',
 passDoNotMatch: "Passwords don't match! 😅",
 noInternet : 'Internet connection not available',
 welcme : 'Welcome to PillPal! 🎉',


} as const;