import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: '#F5F3FF',
    },
    screenBg: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    centerWrap: {
        width: '100%',
        maxWidth: 420,
        alignItems: 'center',
    }, passwordInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        paddingHorizontal: 14,
        backgroundColor: 'white',
    },

    passwordInputInner: {
        flex: 1,
        paddingVertical: 14,
        fontSize: 16,
        color: '#111827',
    },

    eyeIcon: {
        fontSize: 18,
        marginLeft: 8,
    },
    errorInput: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FCA5A5',
    },
    errorText: {
        marginTop: 6,
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '700',
        color: '#EF4444',
    },
    phoneShell: {
        width: '100%',
        minHeight: 780,
        maxHeight: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: 40,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.8)',
        shadowColor: '#C4B5FD',
        shadowOpacity: 0.35,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 12 },
        elevation: 12,
    },
    topGradientBar: {
        height: 6,
        width: '100%',
        backgroundColor: '#7C3AED',
    },
    notchWrap: {
        alignItems: 'center',
        paddingTop: 12,
        paddingBottom: 4,
    },
    notch: {
        width: 96,
        height: 4,
        borderRadius: 999,
        backgroundColor: '#E5E7EB',
    },
    blob: {
        position: 'absolute',
    },
    content: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: 24,
    },
    section: {
        marginBottom: 16,
    },
    logoRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    logoText: {
        fontSize: 32,
        fontWeight: '900',
        letterSpacing: -0.8,
        color: '#7C3AED',
    },
    logoPillEmoji: {
        fontSize: 24,
    },
    logoSubText: {
        textAlign: 'center',
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '600',
        marginTop: 4,
    },

    mascotSection: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 6,
        marginBottom: 10,
        minHeight: 140,
    },
    streakBanner: {
        borderRadius: 20,
        padding: 14,
        shadowColor: '#FDBA74',
        shadowOpacity: 0.45,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 5,
    },
    bannerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    bannerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        paddingRight: 10,
    },
    bannerTrophy: {
        fontSize: 22,
        marginRight: 8,
    },
    bannerTitle: {
        color: '#FFFFFF',
        fontWeight: '800',
        fontSize: 13,
        lineHeight: 16,
    },
    bannerSubtitle: {
        color: '#FFEDD5',
        fontSize: 11,
        marginTop: 2,
    },
    bannerBadge: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    bannerBadgeEmoji: {
        fontSize: 18,
        lineHeight: 20,
    },
    bannerBadgeText: {
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: '800',
        marginTop: 2,
    },
    badgesHeading: {
        textAlign: 'center',
        color: '#9CA3AF',
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 10,
    },
    badgesRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
    },
    badgeItem: {
        alignItems: 'center',
        flex: 1,
    },
    badgeCircle: {
        width: 44,
        height: 44,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        position: 'relative',
    },
    badgeEmoji: {
        fontSize: 18,
        opacity: 0.4,
    },
    badgeOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(243,244,246,0.7)',
    },
    badgeLock: {
        position: 'absolute',
        fontSize: 11,
        color: '#9CA3AF',
    },
    badgeLabel: {
        fontSize: 9,
        color: '#9CA3AF',
        fontWeight: '500',
        marginTop: 4,
    },

    emailInput: {
        backgroundColor: '#F5F3FF',
        borderColor: '#E9D5FF',
    },
    emailInputFocused: {
        backgroundColor: '#FFFFFF',
        borderColor: '#A78BFA',
        shadowColor: '#C4B5FD',
        shadowOpacity: 0.35,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 4,
    },
    passwordInput: {
        backgroundColor: '#FDF2F8',
        borderColor: '#FBCFE8',
    },
    passwordEye: {
        // position: 'absolute',
        // right: 12,
        // top: '50%',
        // transform: [{ translateY: -10 }],
        position: 'absolute',
        right: 12,
        top: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        width: 36,
        zIndex: 5
    },


    passwordInputFocused: {
        backgroundColor: '#FFFFFF',
        borderColor: '#F472B6',
        shadowColor: '#F9A8D4',
        shadowOpacity: 0.35,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 4,
    },
    forgotWrap: {
        alignItems: 'flex-end',
        marginTop: 2,
    },
    forgotText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#8B5CF6',
    },
    loginButtonOuter: {
        borderRadius: 18,
        overflow: 'hidden',
        shadowColor: '#C4B5FD',
        shadowOpacity: 0.45,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    loginButton: {
        paddingVertical: 16,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 18,
    },
    loginInnerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginLoadingEmoji: {
        fontSize: 18,
        marginRight: 8,
    },
    loginButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '900',
    },
    dividerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#F3F4F6',
    },
    dividerText: {
        fontSize: 12,
        color: '#9CA3AF',
        fontWeight: '500',
    },
    signupWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    signupText: {
        fontSize: 14,
        color: '#6B7280',
    },
    signupLink: {
        fontSize: 14,
        fontWeight: '900',
        color: '#8B5CF6',
    },
    bottomCard: {
        backgroundColor: '#ECFDF5',
        borderColor: '#D1FAE5',
        borderWidth: 1,
        borderRadius: 18,
        padding: 14,
        alignItems: 'center',
    },
    bottomCardTitle: {
        textAlign: 'center',
        color: '#047857',
        fontSize: 12,
        fontWeight: '700',
    },
    bottomCardSubtitle: {
        marginTop: 4,
        textAlign: 'center',
        color: '#10B981',
        fontSize: 10,
    },
    bottomCardBold: {
        fontWeight: '900',
        color: '#047857',
    },
    bottomSpacer: {
        height: 12,
    },
});